
---
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: Remove packages not needed anymore
    apt:
      autoremove: yes

  - name: Update all installed packages using APT module
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
      force_apt_get: true
    register: apt_update_status

  - name: 'Update all packages'
    command: "apt-get -y update -o Dpkg::Options::='force-confdef' -o Dpkg::Options::='force-confold' "
    register: apt_update_status

  - name: Upgrade all installed packages
    command: "apt-get -y full-upgrade -o Dpkg::Options::='force-confdef' -o Dpkg::Options::='force-confold' "
    register: apt_upgrade_status


  - name: Reboot when packages were updated & Upgraded
    reboot:
      post_reboot_delay: 60
    when: apt_update_status.changed == apt_upgrade_status.changed
